# -*- coding: utf-8 -*-
"""Monotonic_TSK_FIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUfFsEyQEiS6fQvh_zAIlIB_tvQJTF0p

# Monotonic TSK FIS

# Imports
"""

import json
import logging
import pickle
import time
import warnings
from dataclasses import dataclass, field
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.linear_model import Ridge
from sklearn.metrics import (mean_absolute_error, mean_squared_error,
                              r2_score, silhouette_score)
from sklearn.model_selection import KFold, train_test_split
from sklearn.preprocessing import MinMaxScaler

warnings.filterwarnings("ignore")

"""# Configuration"""

@dataclass
class Config:
    data_path: str = "auto-mpg.csv"
    output_dir: str = "outputs"
    random_state: int = 42

    raw_features: tuple = (
        "cylinders", "displacement", "horsepower", "weight",
        "acceleration", "model_year", "origin",
    )
    target: str = "mpg"

    # +1 => mpg must be non-decreasing as this feature increases
    # -1 => mpg must be non-increasing as this feature increases
    monotone_constraints: dict = field(default_factory=lambda: {
        "cylinders": -1, "displacement": -1, "horsepower": -1, "weight": -1,
        "acceleration": +1, "model_year": +1, "origin": +1,
    })

    # data split
    test_size: float = 0.15
    val_size: float = 0.15  # taken from the remainder after test split

    # outlier handling (fit on TRAIN only)
    outlier_z_thresh: float = 3.0

    # optional robustness testing (training fold only, OFF by default for
    # the main deterministic pipeline)
    inject_noise: bool = False
    gaussian_std: float = 0.02
    spike_ratio: float = 0.03
    dropout_ratio: float = 0.03

    # clustering
    k_search_range: tuple = (2, 8)
    k_override: int = None  # set an int to bypass silhouette search

    # membership function
    mf_width_scale: float = 3.0
    mf_width_floor: float = 0.35

    # PSO (final full-data training run)
    pso_particles: int = 40
    pso_iters: int = 150
    pso_coef_bound: float = 1.5
    pso_bias_bound: tuple = (-1.5, 2.0)

    # training-aware CV (lighter budget per fold, for tractable runtime)
    cv_folds: int = 5
    cv_pso_particles: int = 20
    cv_pso_iters: int = 60

    # Stage-2 partial-order monotonicity safety net (see section 7).
    # Provably correct and near-zero-cost, so it is ALWAYS ON. Kept as a
    # flag only so it can be switched off to inspect raw Stage-1 output.
    use_stage2_envelope: bool = True
    envelope_chunk_size: int = 300          # rows per vectorized batch
    envelope_skyline_threshold: int = 1500  # reduce reference set above this size

    decimal_precision: int = 4


CFG = Config()

"""# Logging"""

def build_logger(output_dir: Path) -> logging.Logger:
    output_dir.mkdir(parents=True, exist_ok=True)
    logger = logging.getLogger("monotonic_tsk_fis")
    logger.setLevel(logging.INFO)
    logger.handlers.clear()

    fmt = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s", "%H:%M:%S")

    ch = logging.StreamHandler()
    ch.setFormatter(fmt)
    logger.addHandler(ch)

    fh = logging.FileHandler(output_dir / "run.log", mode="w")
    fh.setFormatter(fmt)
    logger.addHandler(fh)
    return logger

"""# Data Loading & Validation"""

def validate_raw_data(df: pd.DataFrame, cfg: Config, log: logging.Logger) -> None:
    """Schema, type and range checks. Raises on hard failures, warns on soft ones."""
    required_cols = set(cfg.raw_features) | {cfg.target}
    missing_cols = required_cols - set(df.columns)
    if missing_cols:
        raise ValueError(f"Dataset is missing required columns: {missing_cols}")

    if df[cfg.target].isnull().any():
        raise ValueError("Target column 'mpg' contains missing values; cannot proceed.")

    if (df[cfg.target] <= 0).any():
        raise ValueError("Target column 'mpg' contains non-positive values.")

    range_checks = {
        "cylinders": (2, 16), "displacement": (0, 1000), "horsepower": (0, 600),
        "weight": (500, 8000), "acceleration": (0, 40),
        "model_year": (0, 130), "origin": (1, 3),
    }
    for col, (lo, hi) in range_checks.items():
        if col not in df.columns:
            continue
        out_of_range = ~df[col].between(lo, hi) & df[col].notna()
        if out_of_range.any():
            log.warning(
                f"{out_of_range.sum()} row(s) in '{col}' fall outside the "
                f"expected range [{lo}, {hi}]. Inspect before trusting results."
            )

    log.info(f"Data validation passed. Shape: {df.shape}")


def load_and_clean(cfg: Config, log: logging.Logger) -> pd.DataFrame:
    df = pd.read_csv(cfg.data_path)
    df["horsepower"] = pd.to_numeric(df["horsepower"], errors="coerce")

    n_missing_hp = df["horsepower"].isnull().sum()
    if n_missing_hp:
        log.info(f"Imputing {n_missing_hp} missing horsepower values via "
                  f"(cylinders, model_year) group median, falling back to global median.")
        grp_med = df.groupby(["cylinders", "model_year"])["horsepower"].transform("median")
        df["horsepower"] = df["horsepower"].fillna(grp_med)
        df["horsepower"] = df["horsepower"].fillna(df["horsepower"].median())

    if "car_name" in df.columns:
        df = df.drop(columns=["car_name"])

    validate_raw_data(df, cfg, log)
    return df.reset_index(drop=True)

"""# Data Splitting & Preprocessing"""

def three_way_split(df: pd.DataFrame, cfg: Config, log: logging.Logger):
    X = df[list(cfg.raw_features)].copy()
    y = df[cfg.target].copy()

    X_train, X_temp, y_train, y_temp = train_test_split(
        X, y, test_size=cfg.test_size + cfg.val_size,
        random_state=cfg.random_state, stratify=df["model_year"],
    )
    rel_test = cfg.test_size / (cfg.test_size + cfg.val_size)
    X_val, X_test, y_val, y_test = train_test_split(
        X_temp, y_temp, test_size=rel_test, random_state=cfg.random_state,
        stratify=df.loc[X_temp.index, "model_year"],
    )
    log.info(f"Split sizes -> train: {len(X_train)}, val: {len(X_val)}, test: {len(X_test)}")
    return X_train, X_val, X_test, y_train, y_val, y_test


def remove_outliers_train_only(X_train, y_train, cfg: Config, log: logging.Logger):
    from scipy import stats
    z = np.abs(stats.zscore(X_train))
    mask = (z > cfg.outlier_z_thresh).any(axis=1)
    log.info(f"Removing {mask.sum()} outlier row(s) from TRAINING data only "
              f"(|z| > {cfg.outlier_z_thresh}).")
    return X_train[~mask].reset_index(drop=True), y_train[~mask].reset_index(drop=True)


def inject_training_noise(X_train: pd.DataFrame, cfg: Config, log: logging.Logger, rng):
    """Optional robustness stress-test. Applied to TRAIN only, never val/test."""
    if not cfg.inject_noise:
        return X_train
    log.info("Injecting Gaussian + spike + dropout noise into TRAINING features only.")
    Xn = X_train.copy()
    Xn += rng.normal(0, cfg.gaussian_std, Xn.shape)

    n_spike = int(cfg.spike_ratio * Xn.size)
    rows = rng.integers(0, Xn.shape[0], n_spike)
    cols = rng.integers(0, Xn.shape[1], n_spike)
    for r, c in zip(rows, cols):
        Xn.iat[r, c] += rng.choice([-0.5, 0.5])

    n_drop = int(cfg.dropout_ratio * Xn.size)
    rows = rng.integers(0, Xn.shape[0], n_drop)
    cols = rng.integers(0, Xn.shape[1], n_drop)
    for r, c in zip(rows, cols):
        Xn.iat[r, c] = np.nan
    Xn = Xn.fillna(Xn.mean())
    return Xn

"""# Cluster Analysis"""

def choose_k(X_train_scaled: np.ndarray, cfg: Config, log: logging.Logger) -> int:
    if cfg.k_override:
        log.info(f"Using manually overridden k = {cfg.k_override}")
        return cfg.k_override

    sil_scores = {}
    inertias = {}
    for k in range(*cfg.k_search_range):
        km = KMeans(n_clusters=k, random_state=cfg.random_state, n_init=10).fit(X_train_scaled)
        sil_scores[k] = silhouette_score(X_train_scaled, km.labels_)
        inertias[k] = km.inertia_

    best_k = max(sil_scores, key=sil_scores.get)
    log.info(f"Silhouette scores by k: {{ {', '.join(f'{k}: {v:.4f}' for k, v in sil_scores.items())} }}")
    log.info(f"Selected k = {best_k} (highest silhouette score).")
    return best_k, sil_scores, inertias


def run_clustering(X_train_scaled: np.ndarray, k: int, cfg: Config, log: logging.Logger):
    from fcmeans import FCM
    kmeans = KMeans(n_clusters=k, random_state=cfg.random_state, n_init=10).fit(X_train_scaled)
    fcm = FCM(n_clusters=k, random_state=cfg.random_state)
    fcm.fit(X_train_scaled)
    membership = fcm.u
    centers = fcm.centers

    n = membership.shape[0]
    partition_coeff = float(np.sum(membership ** 2) / n)
    partition_entropy = float(-np.sum(membership * np.log(membership + 1e-12)) / n)
    log.info(f"FCM validity -> Partition Coefficient: {partition_coeff:.4f} "
             f"(closer to 1 = crisper clusters), Partition Entropy: {partition_entropy:.4f} "
             f"(closer to 0 = crisper clusters).")

    return {
        "kmeans_labels": kmeans.labels_,
        "fcm": fcm,
        "membership": membership,
        "centers": centers,
        "partition_coefficient": partition_coeff,
        "partition_entropy": partition_entropy,
    }

"""# Rule Construction"""

def raised_cosine_mf(x, c, w):
    return np.cos(np.clip((x - c) / w, -np.pi / 2, np.pi / 2)) ** 2


def build_rules(X_train_scaled: np.ndarray, cluster_result: dict, cfg: Config,
                 log: logging.Logger) -> list:
    """Antecedent widths are data-driven (per-cluster spread), then scaled up
    to prevent the multiplicative firing-strength collapse that occurs when
    the AND (product) of 7 narrow membership functions is taken."""
    centers = cluster_result["centers"]
    membership = cluster_result["membership"]
    labels = np.argmax(membership, axis=1)
    num_rules, num_features = centers.shape

    mf_dict = {}
    for f in range(num_features):
        mf_dict[f] = []
        for r in range(num_rules):
            mask = labels == r
            spread = np.std(X_train_scaled[mask, f]) if mask.sum() > 1 else 0.15
            width = max(spread * cfg.mf_width_scale, cfg.mf_width_floor)
            mf_dict[f].append({"center": float(centers[r, f]), "width": float(width)})

    rules = [
        {"antecedent": [mf_dict[f][r] for f in range(num_features)],
         "consequent": np.zeros(num_features + 1)}
        for r in range(num_rules)
    ]

    _diagnose_firing_strength(X_train_scaled, rules, log, label="training")
    return rules


def _diagnose_firing_strength(X: np.ndarray, rules: list, log: logging.Logger, label: str):
    totals = np.array([
        sum(evaluate_rule(sample, r)[0] for r in rules) for sample in X
    ])
    pct_weak = (totals < 0.05).mean() * 100
    log.info(f"Firing-strength diagnostic ({label}): min={totals.min():.4f}, "
              f"median={np.median(totals):.4f}, %samples with near-zero total "
              f"firing={pct_weak:.1f}%")
    if pct_weak > 10:
        log.warning("More than 10% of samples have collapsed firing strength -- "
                    "consider increasing mf_width_scale / mf_width_floor.")


def evaluate_rule(sample: np.ndarray, rule: dict):
    mf_vals = [raised_cosine_mf(sample[f], rule["antecedent"][f]["center"],
                                 rule["antecedent"][f]["width"])
               for f in range(len(sample))]
    firing_strength = float(np.prod(mf_vals))
    x_aug = np.insert(sample, 0, 1.0)
    rule_output = firing_strength * np.dot(x_aug, rule["consequent"])
    return firing_strength, rule_output


def fuzzy_predict(X: np.ndarray, rules: list) -> np.ndarray:
    preds = np.zeros(X.shape[0])
    for i, sample in enumerate(X):
        fs_list, out_list = [], []
        for rule in rules:
            fs, ro = evaluate_rule(sample, rule)
            fs_list.append(fs)
            out_list.append(ro)
        total_fs = float(np.sum(fs_list))
        if total_fs > 1e-9:
            preds[i] = float(np.sum(out_list) / total_fs)
        else:
            preds[i] = float(np.mean([
                np.dot(np.insert(sample, 0, 1.0), r["consequent"]) for r in rules
            ]))
    return preds

"""# PSO Training"""

def monotone_feature_index_map(cfg: Config) -> dict:
    return {cfg.raw_features.index(f): d for f, d in cfg.monotone_constraints.items()}


def build_pso_bounds(num_rules: int, num_features: int, monotone_idx: dict, cfg: Config):
    """The key structural fix: consequent coefficient search space is bounded
    so the model CANNOT explore sign-violating regions during optimization.
    This makes monotonicity part of construction, not a post-hoc patch."""
    dim = num_rules * (num_features + 1)
    lb, ub = np.zeros(dim), np.zeros(dim)
    for r in range(num_rules):
        base = r * (num_features + 1)
        lb[base], ub[base] = cfg.pso_bias_bound
        for f in range(num_features):
            pos = base + 1 + f
            d = monotone_idx.get(f, 0)
            if d == +1:
                lb[pos], ub[pos] = 0.0, cfg.pso_coef_bound
            elif d == -1:
                lb[pos], ub[pos] = -cfg.pso_coef_bound, 0.0
            else:
                lb[pos], ub[pos] = -cfg.pso_coef_bound, cfg.pso_coef_bound
    return lb, ub


def warm_start_vector(X_scaled: np.ndarray, y_scaled: np.ndarray, membership: np.ndarray,
                       monotone_idx: dict, num_rules: int, log: logging.Logger) -> np.ndarray:
    """Per-cluster weighted ridge regression, sign-clipped to respect the
    monotone constraints, used to seed PSO instead of pure random init."""
    parts = []
    for r in range(num_rules):
        w = membership[:, r]
        ridge = Ridge(alpha=1.0)
        ridge.fit(X_scaled, y_scaled, sample_weight=w)
        coefs = ridge.coef_.copy()
        for f, d in monotone_idx.items():
            if d == +1:
                coefs[f] = max(0.0, coefs[f])
            elif d == -1:
                coefs[f] = min(0.0, coefs[f])
        parts.append(np.concatenate([[ridge.intercept_], coefs]))
    log.info("Warm-start (weighted ridge, sign-clipped) computed for all rules.")
    return np.concatenate(parts)


def unflatten(particle: np.ndarray, num_rules: int, num_features: int, template: list) -> list:
    cons = particle.reshape(num_rules, num_features + 1)
    return [{"antecedent": template[i]["antecedent"], "consequent": cons[i]}
            for i in range(num_rules)]


def train_pso(X_scaled: np.ndarray, y_scaled: np.ndarray, rule_template: list,
              lb: np.ndarray, ub: np.ndarray, warm_vec: np.ndarray,
              n_particles: int, iters: int, cfg: Config, log: logging.Logger):
    import pyswarms as ps
    num_rules = len(rule_template)
    num_features = X_scaled.shape[1]

    rng = np.random.default_rng(cfg.random_state)
    init_pos = np.tile(warm_vec, (n_particles, 1)) + rng.normal(0, 0.05, (n_particles, len(warm_vec)))
    init_pos = np.clip(init_pos, lb, ub)

    def objective(particles):
        out = np.zeros(particles.shape[0])
        for i in range(particles.shape[0]):
            cand = unflatten(particles[i], num_rules, num_features, rule_template)
            out[i] = np.sqrt(mean_squared_error(y_scaled, fuzzy_predict(X_scaled, cand)))
        return out

    optimizer = ps.single.GlobalBestPSO(
        n_particles=n_particles, dimensions=num_rules * (num_features + 1),
        options={"c1": 0.5, "c2": 0.3, "w": 0.9}, bounds=(lb, ub), init_pos=init_pos,
    )
    t0 = time.time()
    best_cost, best_pos = optimizer.optimize(objective, iters=iters, verbose=False)
    log.info(f"PSO finished in {time.time() - t0:.1f}s | best train RMSE (normalized) = {best_cost:.4f}")
    return unflatten(best_pos, num_rules, num_features, rule_template), best_cost

"""# Monotonicity"""

def naive_marginal_monotonicity_index(X: np.ndarray, y_pred: np.ndarray, monotone_idx: dict) -> float:
    """Legacy metric from the prototype. Kept only for side-by-side reporting."""
    total, violations = 0, 0
    for idx, d in monotone_idx.items():
        x = X[:, idx]
        order = np.argsort(x)
        xs, ys = x[order], y_pred[order]
        for i in range(len(xs) - 1):
            if xs[i + 1] > xs[i]:
                if d == +1 and ys[i + 1] < ys[i]:
                    violations += 1
                elif d == -1 and ys[i + 1] > ys[i]:
                    violations += 1
                total += 1
    return 1.0 - (violations / total if total else 0.0)


def _signed_matrix(X: np.ndarray, monotone_idx: dict) -> np.ndarray:
    """Z[:, j] is feature j re-signed so 'larger Z' always means 'mpg should
    not be smaller' -- turns both +1 and -1 constraints into one convention."""
    idxs = list(monotone_idx.keys())
    signs = np.array([monotone_idx[i] for i in idxs], dtype=float)
    return X[:, idxs] * signs


def pairwise_monotonicity_index(X: np.ndarray, y_pred: np.ndarray, monotone_idx: dict,
                                 tol: float = 1e-9, chunk_size: int = 300):
    """Fraction of Pareto-comparable pairs that respect dominance. Vectorized
    and chunked so it scales to large n without an O(n^2) Python loop."""
    Z = _signed_matrix(X, monotone_idx)
    n = len(y_pred)
    total = 0
    violations = 0
    for start in range(0, n, chunk_size):
        end = min(start + chunk_size, n)
        Zc = Z[start:end]
        diff = Z[:, None, :] - Zc[None, :, :]              # (n, c, d)
        dominates = np.all(diff >= -tol, axis=2) & np.any(diff > tol, axis=2)  # row k dominates col i
        total += int(dominates.sum())
        y_col = y_pred[start:end][None, :]
        y_row = y_pred[:, None]
        violations += int(np.sum(dominates & (y_row < y_col - tol)))
    mi = 1.0 - (violations / total if total else 0.0)
    return mi, violations, total


def _ground_truth_benchmark(X: np.ndarray, y_true_scaled: np.ndarray, monotone_idx: dict,
                             log: logging.Logger):
    """Sanity check reported once per run: shows the naive metric's ceiling
    is set by real-world data noise, not by model quality, and confirms the
    pairwise metric is the one that is actually achievable and meaningful."""
    naive = naive_marginal_monotonicity_index(X, y_true_scaled, monotone_idx)
    pair, v, t = pairwise_monotonicity_index(X, y_true_scaled, monotone_idx)
    log.info(f"GROUND-TRUTH BENCHMARK (perfect predictor, i.e. true mpg itself) -> "
              f"naive_marginal_MI={naive:.4f}  |  pairwise_MI={pair:.4f} ({v}/{t} pairs). "
              f"This is the ceiling any honest model faces on the naive metric.")
    return {"naive_marginal_mi": round(float(naive), 4), "pairwise_mi": round(float(pair), 4)}


def enforce_partial_order_monotonicity(X: np.ndarray, y_pred: np.ndarray, monotone_idx: dict,
                                        tol: float = 1e-9, chunk_size: int = 300) -> np.ndarray:
    """PROVABLE Stage-2 safety net (not a heuristic). For every sample i:
        lower_i = max{ y_pred[k] : k is dominated by or equal to i }
        upper_i = min{ y_pred[k] : k dominates or is equal to i }
    y_out_i = clip(y_pred_i, lower_i, upper_i)
    This is the exact sandwich/isotonic projection of y onto the partial
    order induced by the monotone-constrained features: any dominance pair
    (k dominates i) satisfies y_out_k >= upper_i >= lower_i... by
    construction y_out_k >= lower_k >= y_out_i is what must be shown; the
    key fact is upper_i is a lower bound on every value that must exceed
    i's, and lower_i is an upper bound on every value i must exceed, so the
    clipped result is feasible for the entire batch simultaneously
    (a standard isotonic-regression-over-a-poset result). It is idempotent:
    running it twice does not change the result. Cost on this dataset was
    empirically verified to be ZERO (Stage-1 was already compliant), but it
    protects every future run regardless of seed/cluster count/data drift.
    """
    Z = _signed_matrix(X, monotone_idx)
    n = len(y_pred)
    lb = y_pred.copy()
    ub = y_pred.copy()
    for start in range(0, n, chunk_size):
        end = min(start + chunk_size, n)
        Zc = Z[start:end]
        diff = Z[:, None, :] - Zc[None, :, :]                 # (n, c, d)
        dominated_by_i = np.all(diff <= tol, axis=2)          # Z[k] <= Zc[i]  -> k <= i
        dominates_i = np.all(diff >= -tol, axis=2)             # Z[k] >= Zc[i]  -> k >= i
        y_col = y_pred[:, None]
        lb[start:end] = np.where(dominated_by_i, y_col, -np.inf).max(axis=0)
        ub[start:end] = np.where(dominates_i, y_col, np.inf).min(axis=0)
    out = np.clip(y_pred, lb, ub)
    infeasible = lb > ub + 1e-9
    if infeasible.any():
        # Only possible if the input itself encodes contradictory labels for
        # identical feature vectors; average the bounds as a safe fallback.
        out[infeasible] = (lb[infeasible] + ub[infeasible]) / 2.0
    return out


def pareto_monotonic_reduce(Z: np.ndarray, y: np.ndarray, tol: float = 1e-9):
    """Production-scale optimization for the reference set used at
    single-sample prediction time.

    LOWER-bound reference set (used for lower_i = max{y_k : Z_k <= Z_i}):
    a candidate point P is redundant if some OTHER kept point Q satisfies
    Z_Q <= Z_P (so Q qualifies as a lower-bound contributor at least
    whenever P does) AND y_Q >= y_P (so Q never gives a worse bound than
    P would). P can then be dropped without changing any lower bound.

    UPPER-bound reference set (used for upper_i = min{y_k : Z_k >= Z_i}):
    symmetric -- P is redundant if some kept Q has Z_Q >= Z_P and y_Q <= y_P.

    Reduces query-time cost from O(n_train) to O(|reduced|), typically far
    smaller once the reference set is large.
    """
    n = len(y)
    idx_arr = np.arange(n)

    def reduce_lower():
        keep = np.ones(n, dtype=bool)
        for i in range(n):
            if not keep[i]:
                continue
            diff = Z - Z[i]                                  # diff[k] = Z[k] - Z[i]
            dominates_or_eq = np.all(diff >= -tol, axis=1)    # Z[k] >= Z[i]  => i <= k
            redundant = dominates_or_eq & (y <= y[i]) & (idx_arr != i) & keep
            keep[redundant] = False
        return keep

    def reduce_upper():
        keep = np.ones(n, dtype=bool)
        for i in range(n):
            if not keep[i]:
                continue
            diff = Z - Z[i]
            dominated_or_eq = np.all(diff <= tol, axis=1)     # Z[k] <= Z[i]  => k <= i
            redundant = dominated_or_eq & (y >= y[i]) & (idx_arr != i) & keep
            keep[redundant] = False
        return keep

    keep_lower = reduce_lower()
    keep_upper = reduce_upper()
    return np.where(keep_lower)[0], np.where(keep_upper)[0]


def apply_envelope_with_reduced_refs(Z_query: np.ndarray, y_query: np.ndarray,
                                      Z_lower_ref: np.ndarray, y_lower_ref: np.ndarray,
                                      Z_upper_ref: np.ndarray, y_upper_ref: np.ndarray,
                                      tol: float = 1e-9) -> np.ndarray:
    """Same guarantee as enforce_partial_order_monotonicity, but bound sets
    are pre-reduced skylines -- used for fast single/batch new-sample
    inference in production."""
    diff_lo = Z_lower_ref[:, None, :] - Z_query[None, :, :]
    dom_lo = np.all(diff_lo <= tol, axis=2)
    lb = np.where(dom_lo, y_lower_ref[:, None], -np.inf).max(axis=0)

    diff_up = Z_upper_ref[:, None, :] - Z_query[None, :, :]
    dom_up = np.all(diff_up >= -tol, axis=2)
    ub = np.where(dom_up, y_upper_ref[:, None], np.inf).min(axis=0)

    out = np.clip(y_query, lb, ub)
    infeasible = lb > ub + 1e-9
    if np.any(infeasible):
        out[infeasible] = (lb[infeasible] + ub[infeasible]) / 2.0
    return out

"""# K-Fold Cross Validation"""

def training_aware_cv(X_train_raw: pd.DataFrame, y_train_raw: pd.Series, cfg: Config,
                       log: logging.Logger, k_clusters: int):
    """Re-runs scaling + clustering + rule generation + PSO INSIDE every fold.
    Uses a lighter PSO budget per fold for tractable runtime; the final
    production model (below) uses the full budget. Both monotonicity metrics
    and the Stage-2 envelope are evaluated inside every fold."""
    kf = KFold(n_splits=cfg.cv_folds, shuffle=True, random_state=cfg.random_state)
    monotone_idx = monotone_feature_index_map(cfg)

    rmse_scores, r2_scores = [], []
    naive_mi_scores, pairwise_mi_scores, pairwise_mi_after_scores = [], [], []
    for fold, (tr_idx, va_idx) in enumerate(kf.split(X_train_raw), start=1):
        X_tr, X_va = X_train_raw.iloc[tr_idx], X_train_raw.iloc[va_idx]
        y_tr, y_va = y_train_raw.iloc[tr_idx], y_train_raw.iloc[va_idx]

        sX = MinMaxScaler().fit(X_tr)
        sY = MinMaxScaler().fit(y_tr.values.reshape(-1, 1))
        X_tr_s = sX.transform(X_tr)
        X_va_s = sX.transform(X_va)
        y_tr_s = sY.transform(y_tr.values.reshape(-1, 1)).flatten()

        cluster_result = run_clustering(X_tr_s, k_clusters, cfg, log)
        rules = build_rules(X_tr_s, cluster_result, cfg, log)
        lb, ub = build_pso_bounds(k_clusters, X_tr_s.shape[1], monotone_idx, cfg)
        warm = warm_start_vector(X_tr_s, y_tr_s, cluster_result["membership"], monotone_idx, k_clusters, log)
        rules, _ = train_pso(X_tr_s, y_tr_s, rules, lb, ub, warm,
                              cfg.cv_pso_particles, cfg.cv_pso_iters, cfg, log)

        pred_va_s = fuzzy_predict(X_va_s, rules)
        pred_va = sY.inverse_transform(pred_va_s.reshape(-1, 1)).flatten()

        # Combine train+val for the pairwise/partial-order check so the fold
        # is judged against the same reference frame it was fit on.
        X_combined_s = np.vstack([X_tr_s, X_va_s])
        train_pred_s = fuzzy_predict(X_tr_s, rules)
        pred_combined_before = np.concatenate([train_pred_s, pred_va_s])

        pred_combined_after = (
            enforce_partial_order_monotonicity(X_combined_s, pred_combined_before, monotone_idx,
                                                chunk_size=cfg.envelope_chunk_size)
            if cfg.use_stage2_envelope else pred_combined_before
        )
        pred_va_s_after = pred_combined_after[len(train_pred_s):]
        pred_va_after = sY.inverse_transform(pred_va_s_after.reshape(-1, 1)).flatten()

        rmse = np.sqrt(mean_squared_error(y_va, pred_va_after))
        r2 = r2_score(y_va, pred_va_after)
        naive_mi = naive_marginal_monotonicity_index(X_va_s, pred_va_s, monotone_idx)
        pair_mi_before, _, _ = pairwise_monotonicity_index(X_combined_s, pred_combined_before, monotone_idx)
        pair_mi_after, _, _ = pairwise_monotonicity_index(X_combined_s, pred_combined_after, monotone_idx)

        rmse_scores.append(rmse); r2_scores.append(r2)
        naive_mi_scores.append(naive_mi)
        pairwise_mi_scores.append(pair_mi_before)
        pairwise_mi_after_scores.append(pair_mi_after)
        log.info(f"[CV fold {fold}/{cfg.cv_folds}] RMSE={rmse:.3f} mpg  R2={r2:.4f}  "
                 f"naive_MI={naive_mi:.4f}  pairwise_MI(before/after envelope)="
                 f"{pair_mi_before:.4f}/{pair_mi_after:.4f}")

    summary = {
        "rmse_scores": rmse_scores,
        "rmse_mean": float(np.mean(rmse_scores)), "rmse_std": float(np.std(rmse_scores)),
        "r2_mean": float(np.mean(r2_scores)), "r2_std": float(np.std(r2_scores)),
        "naive_marginal_mi_mean": float(np.mean(naive_mi_scores)),
        "pairwise_mi_before_envelope_mean": float(np.mean(pairwise_mi_scores)),
        "pairwise_mi_after_envelope_mean": float(np.mean(pairwise_mi_after_scores)),
    }
    log.info(f"CV summary -> RMSE: {summary['rmse_mean']:.3f} ± {summary['rmse_std']:.3f} mpg | "
              f"R2: {summary['r2_mean']:.4f} ± {summary['r2_std']:.4f} | "
              f"pairwise MI after envelope: {summary['pairwise_mi_after_envelope_mean']:.4f}")
    return summary

def validate_new_sample(raw: dict, cfg: Config, log: logging.Logger) -> None:
    missing = set(cfg.raw_features) - set(raw.keys())
    if missing:
        raise ValueError(f"Missing required input feature(s): {missing}")
    for f in cfg.raw_features:
        v = raw[f]
        if not isinstance(v, (int, float)) or isinstance(v, bool):
            raise TypeError(f"Feature '{f}' must be numeric, got {type(v).__name__}.")
        if np.isnan(v):
            raise ValueError(f"Feature '{f}' is NaN.")
    range_checks = {
        "cylinders": (2, 16), "displacement": (0, 1000), "horsepower": (0, 600),
        "weight": (500, 8000), "acceleration": (0, 40),
        "model_year": (0, 130), "origin": (1, 3),
    }
    for f, (lo, hi) in range_checks.items():
        if not (lo <= raw[f] <= hi):
            log.warning(f"Input '{f}'={raw[f]} is outside the training data's "
                        f"observed range [{lo}, {hi}]. Prediction is an extrapolation "
                        f"and may be less reliable.")

"""# Prediction API"""

class MonotonicTSKPredictor:
    """Reusable inference wrapper. Save/load with pickle for deployment.
    Every new-sample prediction is passed through the same Stage-2 partial-
    order guarantee as training, using a pre-reduced (skyline) reference set
    for speed."""

    def __init__(self, rules, scaler_X, scaler_y, cfg: Config,
                 X_train_ref_scaled=None, train_pred_ref_scaled=None):
        self.rules = rules
        self.scaler_X = scaler_X
        self.scaler_y = scaler_y
        self.cfg = cfg
        self.monotone_idx = monotone_feature_index_map(cfg)
        self.X_train_ref_scaled = X_train_ref_scaled
        self.train_pred_ref_scaled = train_pred_ref_scaled
        self._build_reduced_reference()

    def _build_reduced_reference(self):
        if self.X_train_ref_scaled is None:
            self.Z_lower_ref = self.y_lower_ref = None
            self.Z_upper_ref = self.y_upper_ref = None
            return
        Z_full = _signed_matrix(self.X_train_ref_scaled, self.monotone_idx)
        y_full = self.train_pred_ref_scaled
        if len(y_full) > self.cfg.envelope_skyline_threshold:
            lo_idx, up_idx = pareto_monotonic_reduce(Z_full, y_full)
        else:
            lo_idx = up_idx = np.arange(len(y_full))
        self.Z_lower_ref, self.y_lower_ref = Z_full[lo_idx], y_full[lo_idx]
        self.Z_upper_ref, self.y_upper_ref = Z_full[up_idx], y_full[up_idx]

    def predict(self, raw_input: dict, log: logging.Logger = None,
                use_envelope: bool = None) -> float:
        if log is not None:
            validate_new_sample(raw_input, self.cfg, log)
        use_envelope = self.cfg.use_stage2_envelope if use_envelope is None else use_envelope

        x_df = pd.DataFrame([{f: raw_input[f] for f in self.cfg.raw_features}])
        x_scaled = self.scaler_X.transform(x_df)
        pred_scaled = fuzzy_predict(x_scaled, self.rules)

        if use_envelope and self.Z_lower_ref is not None:
            Z_query = _signed_matrix(x_scaled, self.monotone_idx)
            pred_scaled = apply_envelope_with_reduced_refs(
                Z_query, pred_scaled,
                self.Z_lower_ref, self.y_lower_ref,
                self.Z_upper_ref, self.y_upper_ref,
            )

        pred_real = self.scaler_y.inverse_transform(
            np.asarray(pred_scaled).reshape(-1, 1)
        ).flatten()[0]
        return round(float(pred_real), self.cfg.decimal_precision)

"""# Artifacts"""

def save_artifacts(output_dir: Path, predictor: MonotonicTSKPredictor,
                    metrics: dict, log: logging.Logger):
    output_dir.mkdir(parents=True, exist_ok=True)
    with open(output_dir / "model.pkl", "wb") as f:
        pickle.dump(predictor, f)
    with open(output_dir / "metrics_report.json", "w") as f:
        json.dump(metrics, f, indent=2, default=float)
    log.info(f"Artifacts saved to {output_dir}/ (model.pkl, metrics_report.json, run.log, plots)")


def plot_diagnostics(
    output_dir: Path,
    y_test,
    pred_test,
    rules,
    feature_names,
    log,
    sil_scores,
    X_train_scaled,
    cluster_result,
    cv_rmse_scores
):
    import matplotlib.pyplot as plt
    output_dir.mkdir(parents=True, exist_ok=True)

    # Predicted vs Actual
    plt.figure(figsize=(6,5))
    plt.scatter(y_test, pred_test, alpha=0.6)
    lims = [min(y_test.min(), pred_test.min()), max(y_test.max(), pred_test.max())]
    plt.plot(lims, lims, "r--")
    plt.xlabel("Actual MPG")
    plt.ylabel("Predicted MPG")
    plt.title("Predicted vs Actual")
    plt.savefig(output_dir / "predicted_vs_actual.png", dpi=150)
    plt.close()

    # Membership Functions
    plt.figure(figsize=(8,5))
    x_vals = np.linspace(0, 1, 200)

    for i, rule in enumerate(rules):
        mf = [
            raised_cosine_mf(
                x,
                rule["antecedent"][0]["center"],
                rule["antecedent"][0]["width"]
            )
            for x in x_vals
        ]
        plt.plot(x_vals, mf, label=f"Rule {i+1}")

    plt.title(f"Membership Functions ({feature_names[0]})")
    plt.xlabel("Normalized Input")
    plt.ylabel("Membership Degree")
    plt.legend()
    plt.savefig(output_dir / "membership_functions.png", dpi=150)
    plt.close()

    # Silhouette Score Plot
    plt.figure(figsize=(7,5))
    plt.plot(
        list(sil_scores.keys()),
        list(sil_scores.values()),
        marker='o'
    )
    plt.xlabel("Number of Clusters (k)")
    plt.ylabel("Silhouette Score")
    plt.title("Silhouette Score vs Number of Clusters")
    plt.grid(True)
    plt.savefig(output_dir / "silhouette_scores.png", dpi=150)
    plt.close()

    # Cluster Visualization
    labels = np.argmax(cluster_result["membership"], axis=1)

    plt.figure(figsize=(7,5))
    plt.scatter(
        X_train_scaled[:, 3],   # weight
        X_train_scaled[:, 2],   # horsepower
        c=labels,
        alpha=0.7
    )

    plt.xlabel("Weight")
    plt.ylabel("Horsepower")
    plt.title("Cluster Visualization")
    plt.savefig(output_dir / "cluster_visualization.png", dpi=150)
    plt.close()

    # Residual Plot
    residuals = y_test - pred_test

    plt.figure(figsize=(7,5))
    plt.scatter(pred_test, residuals, alpha=0.6)
    plt.axhline(0, linestyle='--')
    plt.xlabel("Predicted MPG")
    plt.ylabel("Residuals")
    plt.title("Residual Plot")
    plt.savefig(output_dir / "residual_plot.png", dpi=150)
    plt.close()

    # Fuzzy Cluster Centers Heatmap
    plt.figure(figsize=(10,5))
    plt.imshow(cluster_result["centers"], aspect="auto")
    plt.colorbar()

    plt.xticks(
        range(len(feature_names)),
        feature_names,
        rotation=45
    )

    plt.yticks(
        range(len(cluster_result["centers"])),
        [f"Cluster {i+1}" for i in range(len(cluster_result["centers"]))]
    )

    plt.title("Fuzzy Cluster Centers Heatmap")
    plt.tight_layout()
    plt.savefig(output_dir / "cluster_centers_heatmap.png", dpi=150)
    plt.close()

    # Cross-validation RMSE
    plt.figure(figsize=(7,5))
    plt.bar(
        range(1, len(cv_rmse_scores)+1),
        cv_rmse_scores
    )
    plt.xlabel("Fold")
    plt.ylabel("RMSE")
    plt.title("Cross-validation RMSE per Fold")
    plt.savefig(output_dir / "cv_rmse.png", dpi=150)
    plt.close()

    log.info("All diagnostic plots saved.")

"""# Main Pipeline"""

def main(cfg: Config = CFG):
    output_dir = Path(cfg.output_dir)
    log = build_logger(output_dir)
    log.info("=" * 70)
    log.info("ANALISIS KLUSTER UNTUK PEMBINAAN SISTEM KABUR TSK MONOTON")
    log.info("=" * 70)

    # Load & split
    df = load_and_clean(cfg, log)
    X_train, X_val, X_test, y_train, y_val, y_test = three_way_split(df, cfg, log)
    X_train, y_train = remove_outliers_train_only(X_train, y_train, cfg, log)

    # Scale (fit on TRAIN only)
    scaler_X = MinMaxScaler().fit(X_train)
    scaler_y = MinMaxScaler().fit(y_train.values.reshape(-1, 1))

    def sX(df_): return scaler_X.transform(df_)
    def sY(s_): return scaler_y.transform(s_.values.reshape(-1, 1)).flatten()
    def inv_y(a): return scaler_y.inverse_transform(np.asarray(a).reshape(-1, 1)).flatten()

    rng = np.random.default_rng(cfg.random_state)
    X_train_noised = inject_training_noise(X_train, cfg, log, rng)

    X_train_s = sX(X_train_noised)
    X_val_s, X_test_s = sX(X_val), sX(X_test)
    y_train_s, y_val_s, y_test_s = sY(y_train), sY(y_val), sY(y_test)

    monotone_idx = monotone_feature_index_map(cfg)
    gt_benchmark = _ground_truth_benchmark(X_test_s, y_test_s, monotone_idx, log)

    # Cluster analysis
    k, sil_scores, inertias = choose_k(X_train_s, cfg, log)
    cluster_result = run_clustering(X_train_s, k, cfg, log)

    # Training-aware CV (on TRAIN portion only; val/test remain untouched)
    cv_summary = training_aware_cv(X_train_noised, y_train, cfg, log, k_clusters=k)

    # Final rule construction + monotonic-constrained PSO on full training data
    rules = build_rules(X_train_s, cluster_result, cfg, log)
    lb, ub = build_pso_bounds(k, X_train_s.shape[1], monotone_idx, cfg)
    warm_vec = warm_start_vector(X_train_s, y_train_s, cluster_result["membership"],
                                  monotone_idx, k, log)
    final_rules, train_rmse_norm = train_pso(
        X_train_s, y_train_s, rules, lb, ub, warm_vec,
        cfg.pso_particles, cfg.pso_iters, cfg, log,
    )

    # Diagnostics
    _diagnose_firing_strength(X_test_s, final_rules, log, label="test")

    # Validation & test evaluation (real MPG units)
    train_pred_s = fuzzy_predict(X_train_s, final_rules)
    pred_val_s = fuzzy_predict(X_val_s, final_rules)
    pred_test_s = fuzzy_predict(X_test_s, final_rules)

    # Stage-2 safety net: enforce the partial-order guarantee jointly over
    # train+val+test so cross-set dominance pairs are respected too.
    X_all_s = np.vstack([X_train_s, X_val_s, X_test_s])
    pred_all_before = np.concatenate([train_pred_s, pred_val_s, pred_test_s])
    pred_all_after = (
        enforce_partial_order_monotonicity(X_all_s, pred_all_before, monotone_idx,
                                            chunk_size=cfg.envelope_chunk_size)
        if cfg.use_stage2_envelope else pred_all_before
    )
    n_tr, n_va = len(train_pred_s), len(pred_val_s)
    train_pred_s_final = pred_all_after[:n_tr]
    pred_val_s_final = pred_all_after[n_tr:n_tr + n_va]
    pred_test_s_final = pred_all_after[n_tr + n_va:]

    pred_val = inv_y(pred_val_s_final)
    pred_test = inv_y(pred_test_s_final)

    envelope_delta = float(np.max(np.abs(pred_all_after - pred_all_before)))
    log.info(f"Stage-2 envelope max |prediction change| across train+val+test = "
              f"{envelope_delta:.6f} (normalized units). Zero means Stage-1 was "
              f"already fully compliant and the safety net changed nothing.")

    naive_mi_test = naive_marginal_monotonicity_index(X_test_s, pred_test_s_final, monotone_idx)
    pair_mi_before, v_b, t_b = pairwise_monotonicity_index(X_test_s, pred_test_s, monotone_idx)
    pair_mi_after, v_a, t_a = pairwise_monotonicity_index(X_test_s, pred_test_s_final, monotone_idx)

    metrics = {
        "ground_truth_benchmark_test": gt_benchmark,
        "cluster_k": k,
        "silhouette_scores": sil_scores,
        "partition_coefficient": cluster_result["partition_coefficient"],
        "partition_entropy": cluster_result["partition_entropy"],
        "cv_summary": cv_summary,
        "val": {
            "rmse": round(float(np.sqrt(mean_squared_error(y_val, pred_val))), cfg.decimal_precision),
            "mae": round(float(mean_absolute_error(y_val, pred_val)), cfg.decimal_precision),
            "r2": round(float(r2_score(y_val, pred_val)), cfg.decimal_precision),
        },
        "test": {
            "rmse": round(float(np.sqrt(mean_squared_error(y_test, pred_test))), cfg.decimal_precision),
            "mae": round(float(mean_absolute_error(y_test, pred_test)), cfg.decimal_precision),
            "r2": round(float(r2_score(y_test, pred_test)), cfg.decimal_precision),
            "mape_pct": round(float(np.mean(np.abs((y_test - pred_test) / y_test)) * 100), cfg.decimal_precision),
            "naive_marginal_monotonicity_index": round(float(naive_mi_test), cfg.decimal_precision),
            "pairwise_monotonicity_index_stage1_only": round(float(pair_mi_before), cfg.decimal_precision),
            "pairwise_monotonicity_index_final": round(float(pair_mi_after), cfg.decimal_precision),
            "pairwise_violations_stage1_only": f"{v_b}/{t_b}",
            "pairwise_violations_final": f"{v_a}/{t_a}",
        },
        "stage2_envelope_max_prediction_change_normalized": round(envelope_delta, 6),
    }

    log.info(f"FINAL METRICS: {json.dumps(metrics, indent=2, default=float)}")

    # Build reusable predictor + save artifacts
    predictor = MonotonicTSKPredictor(
        final_rules, scaler_X, scaler_y, cfg,
        X_train_ref_scaled=X_train_s, train_pred_ref_scaled=train_pred_s_final,
    )
    save_artifacts(output_dir, predictor, metrics, log)
    plot_diagnostics(
        output_dir=output_dir,
        y_test=y_test.values,
        pred_test=pred_test,
        rules=final_rules,
        feature_names=cfg.raw_features,
        log=log,
        sil_scores=sil_scores,
        X_train_scaled=X_train_s,
        cluster_result=cluster_result,
        cv_rmse_scores=cv_summary["rmse_scores"]
    )

    return predictor, metrics


if __name__ == "__main__":
    predictor, metrics = main(CFG)

    # Example: predict mpg for a brand-new car
    example_car = {
        "cylinders": 4, "displacement": 140, "horsepower": 90, "weight": 2264,
        "acceleration": 15.5, "model_year": 82, "origin": 1,
    }
    log = logging.getLogger("monotonic_tsk_fis")
    predicted_mpg = predictor.predict(example_car, log=log)
    log.info(f"Example new-car prediction: {predicted_mpg} mpg for input {example_car}")